[package]
name = "img2ascii-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
ffmpeg-next = "8.0.0"
image = "0.25.8"
indicatif = "0.18.0"
rayon = "1.11.0"
